### ISSUE TITLE
Background images don't seem to work??

### ISSUE THREAD

**Issue by chrismarino** [golang/gddo#375]
I think background images were just recently added. Don't seem to work here...

**Comment by shurcooL** [comment]
Can you elaborate on what you're referring to?

**Comment by chrismarino** [comment]
Dimitry, sorry for the cryptic message. 

Was trying to use http://go-talks.appspot.com/ and the issue tracker link brought me here. 

Just wanted to put a background image in my slides and I got an Internal Server Error.

Image works fine: 
http://go-talks.appspot.com/github.com/chrismarino/events/image.slide

But the background does not:
http://go-talks.appspot.com/github.com/chrismarino/events/background.slide

**Comment by adg** [comment]
Probably the app hasn't been updated since background image support was
added. cc @campoy

**Comment by campoy** [comment]
New version deployed.

**Comment by chrismarino** [comment]
Thanks @campoy 

However, I just tried it again and now getting this message.

Error accessing api.github.com.
403: (https://api.github.com/repos/xtblog/gotalks/contents/sets.slide)

for https://go-talks.appspot.com/github.com/xtblog/gotalks/sets.slide

And every other .slide file I try.

CM

**Comment by chrismarino** [comment]
Whoops, never mind. Seems to work now. Might have just been a github thing.

Background images work as well, so that's great too!

Thanks
CM

**Comment by shurcooL** [comment]
403 happens when you exceeed API rate limit quota; it gets reset every hour. It sounds like it might've been deployed without a token set, so the rate limit is lower than usual (for unauthenticated requests). Getting 403 right now as well.

**Comment by campoy** [comment]
This is weird, I deployed with client secret, client id, access token ...
I'm investigating again.

**Comment by chrismarino** [comment]
Yea, I got intermittent errors as well.  Seemed to corrrect itself after a few mins...

Separately, the path for the background image does not get set properly. I had to use the full path (which is different from the way .image works).

**Comment by shurcooL** [comment]
(It's also possible to hit the rate limit with an authenticated client too. The limit is significantly higher, 5000 instead of 60 per hour for most requests, but still not unlimited.)

**Comment by campoy** [comment]
The problem seems to be missing auth, but the env variables are deployed
correctly.

Adding logs and checks to figure out when they get lost.

**Comment by campoy** [comment]
Issue fixed, related to environment variables not being available on App
Engine before the first request.
